### ISSUE TITLE
Extension fails when reading version from undefined

### ISSUE THREAD

**Issue by Hoffs** [Hoffs/vscode-versionlens#4]
```
TypeError: Cannot read property 'version' of undefined
    at Object.buildTagsFromVersionMap (c:\Users\bd3991\.vscode\extensions\hoffs.vscode-versionlens-0.25.1\out\extension-bundle.js:1111:77)
    at c:\Users\bd3991\.vscode\extensions\hoffs.vscode-versionlens-0.25.1\out\extension-bundle.js:3171:48
    at runMicrotasks (<anonymous>:null:null)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at Function.all (<anonymous>:null:null)
```

**Comment by Hoffs** [comment]
Resolved by #6
